// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiPNWslQFIuZjBwVwPeqd4AZffY5-IBAQ',
    appId: '1:706506597068:web:ebaf47a357ae5d59ab1869',
    messagingSenderId: '706506597068',
    projectId: 'borane-a6ce6',
    authDomain: 'borane-a6ce6.firebaseapp.com',
    storageBucket: 'borane-a6ce6.firebasestorage.app',
    measurementId: 'G-WKXFF94L0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxoLRzAkq2-VfcclnuHqNfBWkaBLM--Ng',
    appId: '1:706506597068:android:711aa4ec391647edab1869',
    messagingSenderId: '706506597068',
    projectId: 'borane-a6ce6',
    storageBucket: 'borane-a6ce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGd5BHsPQUcBSdWxPZQXeHv3j3Cua1hZo',
    appId: '1:706506597068:ios:050086ef08919335ab1869',
    messagingSenderId: '706506597068',
    projectId: 'borane-a6ce6',
    storageBucket: 'borane-a6ce6.firebasestorage.app',
    iosBundleId: 'com.example.boranemobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGd5BHsPQUcBSdWxPZQXeHv3j3Cua1hZo',
    appId: '1:706506597068:ios:050086ef08919335ab1869',
    messagingSenderId: '706506597068',
    projectId: 'borane-a6ce6',
    storageBucket: 'borane-a6ce6.firebasestorage.app',
    iosBundleId: 'com.example.boranemobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiPNWslQFIuZjBwVwPeqd4AZffY5-IBAQ',
    appId: '1:706506597068:web:f3d63715f38e406dab1869',
    messagingSenderId: '706506597068',
    projectId: 'borane-a6ce6',
    authDomain: 'borane-a6ce6.firebaseapp.com',
    storageBucket: 'borane-a6ce6.firebasestorage.app',
    measurementId: 'G-C1LKCTSYN5',
  );
}
